# Generated by Django 6.0 on 2026-04-11 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(default='user', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('currency', models.IntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('VIP', 'VIP')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_at_time', models.DateTimeField()),
                ('path', models.TextField(blank=True)),
                ('id_station_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_start', to='main.station')),
                ('id_station_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_stop', to='main.station')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_num', models.CharField(max_length=10)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('station_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_in', to='main.station')),
                ('station_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_out', to='main.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train', to='main.train')),
            ],
        ),
    ]
