# Generated by Django 6.0 on 2026-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="vip_data",
            field=models.TextField(blank=True),
        ),
    ]
