# Generated by Django 6.0 on 2026-03-01 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=80, unique=True)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=128)),
                ('role', models.CharField(default='user', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_at_time', models.DateTimeField()),
                ('path', models.TextField(blank=True)),
                ('id_station_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_start', to='main.station')),
                ('id_station_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_stop', to='main.station')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_num', models.CharField(max_length=10)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('station_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_in', to='main.station')),
                ('station_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_out', to='main.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train', to='main.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.users')),
            ],
        ),
    ]
