# Generated by Django 6.0 on 2026-05-23 22:22

import django.utils.timezone
import djmoney.models.fields
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(10, 'USD'), default_currency='USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
