# Generated by Django 6.0 on 2026-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reservation_user_profile_role_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.IntegerField(default=1000),
        ),
    ]
